---

- name: Import ecrypted vars
  include_vars:
    file: users.yml

- name: Users created
  user:
    name:            "{{ user.name }}"
    password:        "{{ user.pass | password_hash('sha512') }}"
    state:           present
    update_password: always
    comment:         "Ansible-generated user"
  loop: "{{ users }}"
  loop_control:
    pause:    5
    loop_var: "user"
  no_log: true